name: lingo
description: Lingo App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  get: ^4.6.5
  dio: ^5.1.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  flutter_spinkit: ^5.2.0
  curved_navigation_bar: ^1.0.3
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IranSans
      fonts:
        - asset: fonts/IRANSans.ttf

